### ISSUE TITLE
[minor] Bug - UI placement for "Next Steps Date" field is out of order

### ISSUE THREAD

**Issue by juliashull** [info442-sp21/h-team#18]
Minor 

When adding a new job, the "Next Step Date" field is out of order and unlike the previous fields. 

Environment it was encountered in Chrome on Windows.

1. Click to add a new job
2. Scroll down to Next Steps Date field

Actual Result in screenshot below:
![image](https://user-images.githubusercontent.com/46457161/119567714-82de0d80-bd61-11eb-8b46-026d1b020667.png)

Expected Results in screenshot below showcasing the Date Applied field:
![image](https://user-images.githubusercontent.com/46457161/119568043-e700d180-bd61-11eb-97c0-ed6f6a9e58f6.png)

**Comment by mariamatlick** [comment]
We will work on aligning the fields of the form to create a seamless experience!

**Comment by yiuchungcheung** [comment]
We have fixed the alignment!
