### ISSUE TITLE
[minor]: Disappearing email box

### ISSUE THREAD

**Issue by embascom** [info442-sp21/h-team#19]
Severity Minor
Description When the user goes to create a new account, when selecting the input box for the email the outline and title disappears.
Environment Chrome on a Windows Laptop
Steps to Reproduce:
- Click on Login
- try to log in without a valid email

**Comment by mariamatlick** [comment]
Duplicate of #16

**Comment by yiuchungcheung** [comment]
This is the form format that we chose to use and it works as it is supposed to, but we understand how this could be confusing! We will look into another form format.
