### ISSUE TITLE
[minor] Large Number Salaries Run Off Page

### ISSUE THREAD

**Issue by smckissick1** [info442-sp21/h-team#23]
Minor

"Salary" section has numbers run off the square of the job application, making them invisible to the user.

Encountered in Chrome v90.0.4430.212 on macOS Big Sur

1. Click "New Application" button
2. Fill out all fields
3. Give Pay Rate section at least 40 digits
4. Click save

Actual Result: Numbers run off the square
Expected Result: Numbers wrap to next line or box size increases

**Comment by mariamatlick** [comment]
We plan on limiting the numbers typed in this box to 7 figures, and we will no longer have this issue

**Comment by yiuchungcheung** [comment]
We have restricted the input field type to be numbers only and limited the characters to be 7 figures!

**Comment by yiuchungcheung** [comment]
https://github.com/info442-sp21/h-team/commit/2ac74bc1b6dc806d6132858eb76e50fe3e70d349

**Comment by cherimarie** [comment]
If users are applying for positions with 40 character salaries, they probably have staff members carving the details into marble slabs for posterity rather than using a common app 😆  Great bug catch, Sierra.
