### ISSUE TITLE
Limit Number of Characters Allowed In Form

### ISSUE THREAD

**Issue by smckissick1** [info442-sp21/h-team#24]
Limit the number of characters in the form so that the user cannot cause issues with character space once displayed on home page.

**Comment by ifrahm** [comment]
Thank you we will consider limiting the characters in the form in a later release

**Comment by ifrahm** [comment]
https://github.com/info442-sp21/h-team/commit/2ac74bc1b6dc806d6132858eb76e50fe3e70d349
