### ISSUE TITLE
[Minor] No way to get back to the landing/sign up page after logging out

### ISSUE THREAD

**Issue by dorilusions** [info442-sp21/h-team#26]
This is in Google Chrome ver. 90.0.4430.212  for desktop.  Not actually sure if this is a bug or enhancement, but after logging out, there seems to be no actual way besides to go back to the landing URL (trackity.info) in the address bar to get to the landing page so that a new user can sign up.  It's a little more intuitive for me to go back to the landing page after signing out so that users can choose to either log in or sign up for a new account.  This would be useful in the situation of if you switch users on your computer, and the new user doesn't have an account and would like to sign up.

**Comment by yiuchungcheung** [comment]
Thank you for the feedback! We will fix the routing to the home page instead of the sign in page.
