### ISSUE TITLE
Having to select job type (part-time, full time, internship etc)

### ISSUE THREAD

**Issue by SandyHsiao** [info442-sp21/h-team#30]
Enable users to select job types can make the application more organized and detailed. It would be useful because users may me applying to multiple different types of job at the same time and might want to keep track of all of them.

**Comment by mariamatlick** [comment]
We plan on doing this!

**Comment by ifrahm** [comment]
https://github.com/info442-sp21/h-team/commit/2ac74bc1b6dc806d6132858eb76e50fe3e70d349
