### ISSUE TITLE
[Enhancement] Upload bar moving the wrong way

### ISSUE THREAD

**Issue by atnguyenduy** [info442-sp21/h-team#35]
**Describe bug**
Upload bar moves from right to left

**To reproduce**
1. Go to https://trackity.info/dashboard
2. Select 'New Application'
3. Fill out application
4. Submit application
5. See error in top right corner

**Expected behavior**
Upload bar moves from left to right 

**Screenshot**
![image](https://user-images.githubusercontent.com/41980535/119576132-05b89580-bd6d-11eb-853d-2bb490389dfd.png)

**Desktop (please complete the following information):**
Device: Lenovo Thinkpad laptop
Windows 10 Enterprise / Version 20H2 / OS build 19042.804
Browser: Edge
Version 90.0.818.56

**Comment by mariamatlick** [comment]
This is not an upload bar, it is indicating how long the notification will be visible. The bar moves from right to left to indicate the time going to 0.
