### ISSUE TITLE
Feature request: switch to create account when log in failed

### ISSUE THREAD

**Issue by changz23-1836696** [info442-sp21/h-team#40]
Requested feature: when the user is trying to log in using a non-registered account, automatically switch to the log-up page.
Explanation: When I log in using a non-registered account, I receive an error message, which is good! But if users do not know if they entered the wrong email or password, going to the log-up page will inform users that they are trying to log in with a new email.

**Comment by yiuchungcheung** [comment]
Thanks for the feedback, we will look into this and see how we can implement this enhancement feature!
