### ISSUE TITLE
Feature request: allow users to go back to the landing page from log in page

### ISSUE THREAD

**Issue by changz23-1836696** [info442-sp21/h-team#41]
Requested feature: In the sign-in/sign-up page, add a button to bring users back to the landing page where the users can re-choose if they want to sign in or sign-up
Explanation: If the users forget their passwords/ accidentally click the login in button without sign up first, they might need a better and clearer way to go back instead of hitting back button on the browser.

**Comment by ifrahm** [comment]
Duplicate of #21
